name: Sync-branch-with-prestaging
on:
  push:
    branches:
      - prestaging

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> upgrade
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: prestaging
          target_branch: prestaging-upgrade
          github_token: ${{ github.token }}
   
